### ISSUE TITLE
Deploying on Heroku

### ISSUE THREAD

**Issue by gary360** [91DarioDev/forwardscoverbot#35]
When turn it on, it always gives this error.

> 2021-04-08T20:29:56.488848+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-08T20:29:56.488850+00:00 app[worker.1]:   File "/app/.heroku/python/bin/forwardscoverbot", line 11, in <module>
2021-04-08T20:29:56.489057+00:00 app[worker.1]:     load_entry_point('forwardscoverbot', 'console_scripts', 'forwardscoverbot')()
2021-04-08T20:29:56.489061+00:00 app[worker.1]:   File "/app/forwardscoverbot/__main__.py", line 59, in main
2021-04-08T20:29:56.489213+00:00 app[worker.1]:     dp.add_handler(MessageHandler(Filters.all, messages.before_processing), 0)
2021-04-08T20:29:56.489245+00:00 app[worker.1]: ***`AttributeError: module 'forwardscoverbot.messages' has no attribute 'before_processing`***

**Comment by 91DarioDev** [comment]
Sorry I never used heroku :(

**Comment by gary360** [comment]
Ok
